// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PMSDb))]
    [Migration("20240530135619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PlayerPokemon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Def")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("PokemonItems");
                });

            modelBuilder.Entity("PlayerPokemon", b =>
                {
                    b.OwnsOne("PlayerPokemonMove", "Move1", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Accuracy")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PP")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.OwnsOne("PlayerPokemonMove", "Move2", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Accuracy")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PP")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.OwnsOne("PlayerPokemonMove", "Move3", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Accuracy")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PP")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.OwnsOne("PlayerPokemonMove", "Move4", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Accuracy")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PP")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Power")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.OwnsOne("PlayerPokemonAbility", "Ability", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.OwnsOne("PlayerPokemonNature", "NatureDetails", b1 =>
                        {
                            b1.Property<int>("PlayerPokemonID")
                                .HasColumnType("INTEGER");

                            b1.Property<float?>("Atk")
                                .HasColumnType("REAL");

                            b1.Property<float?>("Def")
                                .HasColumnType("REAL");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<float?>("SpAtk")
                                .HasColumnType("REAL");

                            b1.Property<float?>("SpDef")
                                .HasColumnType("REAL");

                            b1.Property<float?>("Spd")
                                .HasColumnType("REAL");

                            b1.HasKey("PlayerPokemonID");

                            b1.ToTable("PokemonItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPokemonID");
                        });

                    b.Navigation("Ability")
                        .IsRequired();

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");

                    b.Navigation("NatureDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
