// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PMSDb))]
    partial class PMSDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PlayerPokemon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Def")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Move1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Move2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Move3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Move4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("PokemonItems");
                });
#pragma warning restore 612, 618
        }
    }
}
